name: Publish to NuGet
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: dotnet restore
        run: dotnet restore

      - name: Publish NuGet Package
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: BlendoBot.Core/BlendoBot.Core.csproj
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${{secrets.GIT_TOKEN}}
          NUGET_SOURCE: https://nuget.pkg.github.com/BlendoBot/index.json
          TAG_COMMIT: false